return {
	-- "ravitemer/mcphub.nvim",
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- },
	-- cmd = "MCPHub",
	-- build = "npm install mcp-hub@latest",
	-- config = function()
	-- 	require("mcphub").setup({
	-- 		port = 42690,
	-- 		config = vim.fn.expand("~/.config/mcp/servers.json"),
	--
	-- 		-- Optional options
	-- 		on_ready = function(hub)
	-- 			-- Called when hub is ready
	-- 		end,
	-- 		on_error = function(err)
	-- 			-- Called on errors
	-- 		end,
	-- 		log = {
	-- 			level = vim.log.levels.WARN,
	-- 			to_file = false,
	-- 			file_path = nil,
	-- 			prefix = "MCPHub",
	-- 		},
	-- 	})
	-- end,
}
