# mayu
[colors]
foreground = "#908caa"
background = "#000000"
cursor_bg = "#f5dcd8"
cursor_border = "f5dcd8"
cursor_fg = "#f5dcd8"
selection_bg = "#26233a"
selection_fg = "#e0def4"

ansi = ["#000000","#eb6f92","#3e8fb0","#f6c177","#9ccfd8","#eba4ac","#9ccfd8","#e0def4"]
brights = ["#6e6a86","#eb6f92","#3e8fb0","#f6c177","#9ccfd8","#eba4ac","#9ccfd8","#e0def4"]
